forge: Error if index is dirty
When running `forge pr checkout` if the index is dirty error with an
informational message instead of the current garbage.

Before this patch the error was:

Error: Failed to checkout branch: error: pathspec 'pr-135' did not match any file(s) known to git